### ISSUE TITLE
Force ipv4 / ipv6

### ISSUE THREAD

**Issue by Pea13** [davecheney/httpstat#108]
Hi,

It would be nice to have a -4 / -6 switch to force DNS resolution to ipv4 or ipv6.
Like this, we could compare response time between both protocol.
Regards,

**Comment by davecheney** [comment]
Thank you for raising this issue. If you want to send a PR to add this please do so.

**Comment by moorereason** [comment]
This request was fixed in #126.

**Comment by davecheney** [comment]
Fixed #126
