### ISSUE TITLE
Package exists but is not a directory

### ISSUE THREAD

**Issue by wayneashleyberry** [davecheney/httpstat#120]
I'm getting the following error trying to install this package

```sh
go get -u github.com/davecheney/httpstat
package github.com/davecheney/httpstat/vendor/github.com/fatih/color: /Users/wayne/go/src/github.com/davecheney/httpstat/vendor/github.com/fatih/color/.git exists but is not a directory
package github.com/davecheney/httpstat/vendor/golang.org/x/net/http2: /Users/wayne/go/src/github.com/davecheney/httpstat/vendor/golang.org/x/net/.git exists but is not a directory
```

Tried cleaning my $GOPATH and didn't make a difference.

```sh
sudo rm -r $GOPATH
mkdir $GOPATH
```

#### System Details

```
go version go1.8.1 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/wayne/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8s/j9vt85xs4ps80919tlwsxdk00000gn/T/go-build266113172=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
GOROOT/bin/go version: go version go1.8.1 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.8.1 X:framepointer
uname -v: Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.12.4
BuildVersion:	16E195
lldb --version: lldb-370.0.42
  Swift-3.1
```

**Comment by davecheney** [comment]
Try deleting $GOPATH/src/github.com/davecheney/httpstat and trying again.

**Comment by davecb** [comment]
It looks odd, but builds fine.

**Comment by simplycycling** [comment]
Same issue when I try to do a go get, and deleting $GOPATH/src/github.com/davecheney/httpstat and repeating did not make a difference. I had to do a go build from $GOPATH/src/github.com/davecheney/httpstat.

**Comment by cthulhu** [comment]
Same here, with pretty much same system details. 

    go get -u github.com/davecheney/httpstat

fetches the code but build fails weirdly:

    package github.com/davecheney/httpstat/vendor/github.com/fatih/color: ~/go/src/github.com/davecheney/httpstat/vendor/github.com/fatih/color/.git exists but is not a directory
    package github.com/davecheney/httpstat/vendor/golang.org/x/net/http2: ~/go/src/github.com/davecheney/httpstat/vendor/golang.org/x/net/.git exists but is not a directory

**Comment by wayneashleyberry** [comment]
I'm still getting this error :/

```sh
~
❯ go version
go version go1.8.3 darwin/amd64

~
❯ echo $GOPATH
/Users/wayne/go

~
❯ sudo rm -r $GOPATH/

~
❯ ls $GOPATH
ls: /Users/wayne/go: No such file or directory

~
❯ go get -u github.com/davecheney/httpstat
package github.com/davecheney/httpstat/vendor/github.com/fatih/color: /Users/wayne/go/src/github.com/davecheney/httpstat/vendor/github.com/fatih/color/.git exists but is not a directory
package github.com/davecheney/httpstat/vendor/golang.org/x/net/http2: /Users/wayne/go/src/github.com/davecheney/httpstat/vendor/golang.org/x/net/.git exists but is not a directory

~ 2m 48s
❯
```

**Comment by davecheney** [comment]
This looks like a bug with the -u flag. I'll see about raising a bug upstream.

**Comment by pedromg** [comment]
Just tried here, also confirm the apparent _-u_ flag issue:
- with _-u_ flag it fails with the errors mentioned above (_.../.git exists but is not a directory_);
- without _-u_ flag it works, no errors and builds ok.

notes:
- deleted _$GOPATH/src/github.com/davecheney/httpstat_ between steps
- go version go1.8.3 darwin/amd64
