### ISSUE TITLE
 Multiple Parameters Support ？

### ISSUE THREAD

**Issue by nannanlovelijuan** [davecheney/httpstat#158]
i want I want to ask a question ，why not support Multiple Parameters

```
	args := flag.Args()
	if len(args) != 1 {
		flag.Usage()
		os.Exit(2)
	}
```

**Comment by davecheney** [comment]
No reason that I can recall

**Comment by nannanlovelijuan** [comment]
> No reason that I can recall

Thank you for your answer，If you remember, please let me know

**Comment by davecheney** [comment]
Thinking about it, I don’t see why we couldn’t fetch multiple urls, some settings might not make sense but I figure thats ok

**Comment by nannanlovelijuan** [comment]
> Thinking about it, I don’t see why we couldn’t fetch multiple urls, some settings might not make sense but I figure thats ok

Thank you,Maybe what I want to ask is this support:
```
 httpstat httpbin.org/post -X POST --data-urlencode "a=b" -v
 ```

**Comment by davecheney** [comment]
Oh, i see, you're asking do we support gnu style args; the answer is no, all the parameters with a `-` hyphen have to come before parameters that do not. This is a property of the Go flag package. Sorry

**Comment by nannanlovelijuan** [comment]
> Oh, i see, you're asking do we support gnu style args; the answer is no, all the parameters with a `-` hyphen have to come before parameters that do not. This is a property of the Go flag package. Sorry

Ok，I'm a beginner，Thanks again
