### ISSUE TITLE
Use Github's new Projects feature

### ISSUE THREAD

**Issue by mibk** [davecheney/httpstat#17]
Feel free to close this issue right away. I was just thinking whether the Projects feature wouldn't be more suitable for keeping track of the TODO list (more than the README). I don't have experience with it though.

**Comment by davecheney** [comment]
> I don't have experience with it though.

Neither do I. If someone wants to do that, it would be cool.

**Comment by davecheney** [comment]
I had a quick look at projects. I think it's overkill, README, issues and PR's will do fine for this simple project.
