### ISSUE TITLE
Can't add extra headers

### ISSUE THREAD

**Issue by erfanimani** [davecheney/httpstat#173]
I can't seem to use the `-H` flag, it shows "curl error: curl: option -H: requires parameter":

    $ httpstat -H 'Name: value' https://example.com
    > curl -w <output-format> -D <tempfile> -o <tempfile> -s -S Name: value https://example.com -H
    curl error: curl: option -H: requires parameter
    curl: try 'curl --help' or 'curl --manual' for more information

**Comment by davecheney** [comment]
Thanks for raising this issue. I can't see why curl wold be involved in the output of running httpstat. Is it possible someone has aliased httpstat to curl, or you've installed https://github.com/reorx/httpstat?

**Comment by erfanimani** [comment]
Oops, yes. Sorry!
