### ISSUE TITLE
Httpstat 1.1.0 has not released binary programs

### ISSUE THREAD

**Issue by fcwys** [davecheney/httpstat#177]
Httpstat 1.1.0 has not released binary programs

**Comment by davecheney** [comment]
Thank you for raising this issue. I don't plan to publish binaries. You can build from source with

```
go install github.com/davecheney/httpstat@latest
```

**Comment by fcwys** [comment]
I hope to publish binary programs on GitHub without installing the Golang environment. I hope it will be more convenient to use binary programs. Thanks
