### ISSUE TITLE
Use TLS server name indication

### ISSUE THREAD

**Issue by andres-erbsen** [davecheney/httpstat#39]
https://github.com/davecheney/httpstat/blob/master/main.go#L134 should set `ServerName` in `tls.Config`.

This would make it possible to use this tool with hosting situations where multiple sites share the same IP and there is no fallback.

**Comment by davecheney** [comment]
Yes, this is an important improvement. I think this behaviour should be on by default, see #40 for a suggestion for a flag to disable it.

**Comment by theckman** [comment]
Looks like this may have been closed by #42?

**Comment by davecheney** [comment]
Well spotted.
