### ISSUE TITLE
Limit the number of 30x follows

### ISSUE THREAD

**Issue by jrozner** [davecheney/httpstat#49]
Introduce the -max-directs flag from curl to limit the maximum number for 30x redirects to follow and set a sane default. cURL sets this to 50.

**Comment by davecheney** [comment]
Does this need to be configurable? Can't we just make an arbitrary decision, say 10 and leave it at that?

I don't want to end up rewriting all of curl.

**Comment by jrozner** [comment]
Sure, but the only only additional change to support arbitrary numbers would be adding a flag to change the default number. Also, with the proposes features (not counting all the non HTTP(S) features of cURL that nobody uses) it's not going to be that far off from a functional re-implementation of cURL anyway
