### ISSUE TITLE
Grayscale looks not so legibly on white backgrounded ttys

### ISSUE THREAD

**Issue by n10v** [davecheney/httpstat#5]
I have white background in my terminal and text with grayscale looks not so good on it:
![2016-09-23 16 48 31](https://cloud.githubusercontent.com/assets/13235519/18790130/e7281104-81ad-11e6-82ad-8ed5574135e4.png)
Instead of that, I offer to use usual black text.
And technically `httpstat` will be more simplier :)

**Comment by bogem** [comment]
Some variants:
![2016-09-23 16 57 40](https://cloud.githubusercontent.com/assets/13235519/18790397/eba99ea4-81ae-11e6-9c56-2a9856d51448.png)
![2016-09-23 16 57 48](https://cloud.githubusercontent.com/assets/13235519/18790403/efcecc98-81ae-11e6-8630-35252e579b74.png)

**Comment by davecheney** [comment]
Good poinr.

I'm color blind so I don't really care about colors and just followed the logic that httpstat.py used. I'm find with someone else taking the lead on a better color scheme. See my comments in your PR, basically please vendor fatih's color package and wait for amy to merge her PR first.

**Comment by bogem** [comment]
So what do you think about a change grey text to a simple black text or bold text?
Because grey words look really not so sharp on white background and my screen

**Comment by davecheney** [comment]
I liked the original colour scheme from httpstat.py but I recognise that I usually use a black background and do not have a normal colour vision.

What I would like to see is you prepare a PR and include screenshots of your updated color scheme against various background (white and black appear to be the most common). I'll let other commenters choose.

To be very transparent, colours are subjective and I do not want to see this issue devolve into subjective debate. If no agreement can be reached I will retain the current colour scheme.

**Comment by davecheney** [comment]
@bogem If you want to propose a new color scheme please do so before the 1st of October. Thank you.

**Comment by bogem** [comment]
Ok, I will do it today

**Comment by Alinerenatapereiracosta** [comment]
Quiero aprender adecenbolver todo esto
