### ISSUE TITLE
httpstat -O should handle Content-Disposition: attachment

### ISSUE THREAD

**Issue by davecheney** [davecheney/httpstat#57]
See TODO in `main.readResponseBody`

**Comment by jrozner** [comment]
Happy to take this. Are you content with just regexing out the filename or do you want a full DFA to parse the value?

**Comment by davecheney** [comment]
Regex sounds fine.

**Comment by theckman** [comment]
@jrozner Well, shoot. I just now saw that you called out that you'd take this.
