### ISSUE TITLE
-O / `saveOutput` saves a file for every redirect as well as final response

### ISSUE THREAD

**Issue by ble** [davecheney/httpstat#58]
Tested against a server that redirects, `httpstat -O` wrote one file for each request using that request's URL to determine the output filename.

Possibly don't want to write multiple files if server redirects.
Possibly don't want filename to be controlled by response.

**Comment by ble** [comment]
I have a not-entirely-pertinent, gratuitously redirecting handler that I used to test this out.

**Comment by ble** [comment]
Now I see the `todo`:
https://github.com/davecheney/httpstat/blob/master/main.go#L292

**Comment by theckman** [comment]
Looks like this should be closed by #59.

(I keep looking for things to help with and they are all closed! 😂)
