### ISSUE TITLE
Too many colons

### ISSUE THREAD

**Issue by mholt** [davecheney/httpstat#6]
First, this is awesome, thanks for making a Go version of this!

But it doesn't like when I need to specify a port:

```
httpstat "http://45.56.15.67:8680/"
2016/09/23 09:03:11 unable to resolve host: too many colons in address 45.56.15.67:8680:80
```

(Believe me, I wish this was just on port 80 like every other website. But I'm having connectivity issues to it which is why I thought I'd try httpstat, ha.)

**Comment by ericmdantas** [comment]
The port (`:80` in http case) is being appended no matter what, see: https://github.com/davecheney/httpstat/blob/master/main.go#L86-L100.

**Comment by mholt** [comment]
Yep, you're right. I'd submit a PR right now if I wasn't on my way to class...

**Comment by bogem** [comment]
I think, https://github.com/davecheney/httpstat/pull/7 fixes it too

**Comment by ericmdantas** [comment]
Thanks, I closed mine.

**Comment by davecheney** [comment]
Sorry about that, the logic to split the host and port is very dumb. It needs to be made better.

wrt #7 i'm on the fence about using the httptrace package, see my comments in that PR for details.

If someone wants to have a crack at a better host:port split function, please do so.

**Comment by mholt** [comment]
I have a fix inbound

**Comment by mholt** [comment]
That's strange, why does it show c4f8adb09210466d67a495aebdd5b36d69485e23 in your commit tree?

**Comment by davecheney** [comment]
No idea.
