### ISSUE TITLE
realtime sharing of stat results

### ISSUE THREAD

**Issue by cove** [davecheney/httpstat#62]
would be interesting to have realtime sharing of stats to have more data points when troubleshooting a site. e.g. how did this test compare with others from your AS over the past day, or compared to other ASs, historical error rates. sort of how speedtest.net allows you to see how your download speeds compare to others. would be nice if there was an existing free service that it could just integrate like downdetector.com or netcraft.com, but they don't have free APIs.

**Comment by davecheney** [comment]
Thank you for raising this issue. The original goal for httpstat was to replicate httpstat.py in go, I think we're well on the way to doing this as well as implementing most of the common features of curl. 

With that said, I do not plan to implement this,l request, ita simply too far from the original goal of pretty timing stats from a http request. 

Thank you for your understanding.

**Comment by cove** [comment]
oh yeah, no worries. :) just thought it might be an interesting feature to have on the cli.

**Comment by davecheney** [comment]
It sounds like an interesting project, but it's outside the scope of this
project.
