### ISSUE TITLE
Do you have plan to support proxy?

### ISSUE THREAD

**Issue by mattn** [davecheney/httpstat#67]
But some values of fields may not be a real for latency if httpstat support proxy.

**Comment by davecheney** [comment]
Good question. I think we should handle a proxy, but that may interact with #7 .

**Comment by inkel** [comment]
According to [this StackOverflow answer](http://stackoverflow.com/questions/14661511/setting-up-proxy-for-http-client) it is possible to use a proxy by setting `HTTP_PROXY`. It can also be set programmatically, though perhaps supporting both environment and flag is the most adequate solution.

**Comment by davecheney** [comment]
@inkel at the moment with the hand rolled way of making the connection, negotiating the handshake, then writing the request directly I'm pretty confident that the current code doesn't deal with proxies at all.

Using the httptrace mechanism sounds better, but I'm sure there will be a request to break out the proxy latency, it's connection, it's https handshake, etc.

**Comment by mattn** [comment]
@inkel it's easy to do.

I've implemented this feature in my product.

https://github.com/mattn/http-gonsole/blob/master/http-gonsole.go#L78
