### ISSUE TITLE
error happened where build!

### ISSUE THREAD

**Issue by leeyu** [davecheney/httpstat#74]
main.go:357: undefined: http.MethodHead

$ go version
go version go1.3.1 linux/amd64

**Comment by davecheney** [comment]
Which version of Go are you using. httpstat is tested against the current
stable release, go 1.7.1 and tip.

**Comment by davecheney** [comment]
Oh, is see you are using 1.3.1. httpstat is only tested against 1.7. I'll close this issue with a PR that mentions the installation requirements.

**Comment by joseluisq** [comment]
👍
