### ISSUE TITLE
Revert color work-around

### ISSUE THREAD

**Issue by moorereason** [davecheney/httpstat#75]
We should be able to revert https://github.com/davecheney/httpstat/commit/63dfb1cc0496a03f9356167cb46cc5eb55beb1a7.  A fix has been merged upstream.

See: https://github.com/fatih/color/commit/0016e2689083bc05a71fc0bdcd75f4947f6a5182

**Comment by davecheney** [comment]
@moorereason I've updated the fatih/color dep to pick up the fix. Do you want to take the rest of this ticket ?
