### ISSUE TITLE
Allow writing body to stdout

### ISSUE THREAD

**Issue by op** [davecheney/httpstat#80]
I many times work with curl and pipes eg `curl -v url | jq .`. Why not write the current output to stderr and the body to stdout?

**Comment by davecheney** [comment]
This is a useful feature, but I I think it over reaches the original goal of this tool which was to duplicate httpstat.py in go. The part of httpstat I liked was the nice presentation of the stats, to the point that body is either discarded or written to a random file. 

It is a not my goal to reimplent curl in Go. Thank you for your understanding.
